### PR TITLE
Added searchSlice, viewSlice, updated App and Header for search

### PR DESCRIPTION
**Pull request by Jbhnd**
Added a search component for search results, and view component to switch between the home and search components. Updated App, Header, and Store to complete implementation of the search function.

### CODE REVIEW

**Comment by mattsteen14** [comment]
Hey Joy. This is definitely looking very thorough and comprehensive. You've thought about and implemented a number of things. Could you guide us through how it works with screenshots? Thanks.

**Comment by mattsteen14** [comment]
Hey. So in Header.jsx I think it would be better to change the searchTerm from being set imperatively to declaratively. So instead of:

````
const handleSearch = (e) => {
  e.preventDefault();
  const searchTerm = document.getElementById('search-input').value;
  dispatch(setSearch(searchTerm));
}
````

Declare a state variable searchTermLocal to track the value of the input field. 

```
export const Header = () => {
  const [searchTermLocal, setSearchTermLocal] = useState('');
  const dispatch = useDispatch();

  const handleSearch = (e) => {
    e.preventDefault();
    dispatch(setSearch(searchTermLocal));  // Now using the state variable
  }
```

Then in the return statement:

````
<input 
          type='text' 
          placeholder='Search' 
          aria-label='Search posts'
          value={searchTermLocal} // Controlled input
          onChange={(e) => setSearchTermLocal(e.target.value)}  // Update state on input change
        />
````

This way it becomes a react controlled input & avoids manual DOM operations. 

Make this change and then I will approve.

I think that generally we need to edit a few minor things across the code. I know I implemented some of these these. 

- We don't need isFetching AND isLoading. We can go through the files & cut isFetching.
- I know I edited the error messages from {error.message} because it was returning an error for your web pack compiling but just having {error} is generic. We need to edit to provide more detailed error logging, whether it be reverting to error.message or involving error.status. Let's look at JSON api & createApi documentation to work out the way to go.
- The file structure needs reworking. Lots of slices in /reddit that aren't to do with reddit. I'll have a look at that.

Also a longer term consideration we may need to consider react router if we add more routes to View.

You remember...

```
export default function App() {
  return (
    <Router>
      <Header />
      <main>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/search" element={<Search />} />
          <Route path="/post/:id" element={<PostDetails />} /> {/* Dynamic post ID */}
          <Route path="/subreddits" element={<Subreddits />} />
        </Routes>
      </main>
      <aside>
        <Subreddits />
      </aside>
    </Router>
  );
}
```

**Comment by Jbhnd** [comment]
Hey Matt. Sure.

### Implementation for the search feature.
* Added Search component to display search results, and added View component in App to switch between Home and Search components.
image
image

* User should be able to enter a search term from search bar in header. handleSearch function should update search slice with search term, and update view to 'search'.  Default view is the Home component. On search, the View displays search component.
image
image
image
image

* Searchquery is currently pulling in subreddits that match the searched term. (Note: can change this to pull in the posts that match the search term instead. Up for discussion). So for example, a search for 'reddit' gets results below:
image
image

**Comment by Jbhnd** [comment]
@mattsteen14 
Making the input controlled does make sense. Will update. 

Regarding other points
* For isFetching and isLoading, we might need some type of display to show loading to the user. Another thing to note is if we want the search component displaying posts same way as the home component. For the search component, I used same return details as the home page so that they would look pretty similar for now.
* Agree on reworking the file structure and more detailed error logging.

I also considered adding a router, which is why I went with the search component. If we do decide to switch to a router, we could probably get rid of the view component, and just use routing to switch between views.

**Review by mattsteen14 — APPROVED** [review]
This a gladly approving code review of Joys pull request. You implemented my suggested react controlled search term input state & you even updated the search query to pull in posts instead of subreddits which I didn't realise initially so I was about to ask you to change. We have discussed other things to work on & switching to react router if we add more routes to View. Good work today Joy.

**Pull request merged**
