### PR TITLE
Reddit API rate limits - redditApiSlice - Custom baseQuery to handle rate limit error.

### PR DESCRIPTION
**Pull request by mattsteen14**
Codecademy Reddit Client portfolio project project task:

Add Reddit data
Connect your application to the Reddit API.

When interacting with the API, don’t forget to handle error states.

**Make sure you set up your app to handle errors related to the API rate limits (as mentioned in the Setup tab). See the Hint for ideas!**

_A few ways to work within the rate limits:_

- cache the results of some successful queries, then show those when a query fails
- look for ways to reduce the overall number of queries being made
- provide a front-end error to the user that new data could not be loaded

So apparently createApi() automatically caches queries & it provides built-in caching and deduplication, preventing unnecessary duplicate queries. Then for the last bullet point I believe that I achieved that in my last error state commit as you saw in my posts in the features channel. The user should get a dynamic error response depending on the type of error.

But for handling errors related to API rate limits I have set up a custom baseQuery within redditApiSlice that handles the specific 429 rate limit error. 
Now, I'm not sure how to test this or how I'm supposed to reach limit limit. Apparently it is 10 queries per minute. I keep clicking on different subreddits & searched multiple times (thanks Joy) but nothing different happens. 

I would love your feedback on this. If I'm going in the right direction & if you have any notes.
Do you think we need to account for more error handling scenarios?

### CODE REVIEW

**Comment by Jbhnd** [comment]
Hey @mattsteen14 

Yes, createApi() does seem to cover the first point of caching successful queries, and also preventing duplicate queries.

For the second point, are there more options we can consider for reducing the number of queries?, seeing that rate limit is low for this api. Asking cos I ran into the rate limit error(while looking at your other branch with the post and author icons) after refreshing a few times. Maybe because of the new requests for icons/images. Also, the rate limit error message isn't displaying the correct error message.
image

On testing the limit, I think the limit isn't exactly 10 queries per minute. I ran some requests and looked at the request headers, and below is what I got for the rate limit details. After running one request, there's 495 seconds for 99 requests left. So it seems the rate is more like 100queries within a few minutes. But as I mentioned, refreshing the app(with the icons/images) a few times did hit the rate limit for me.
image

You're definitely on the right track. I think we need to look into ways of reducing the queries, and/or fixing the message displayed for the errors.

**Comment by mattsteen14** [comment]
Thanks Joy. Yes I keep getting that FETCH_ERROR if I'm refreshing. I just pushed an edit to the error message to give a few options to catch the error from the custom baseQuery. Hopefully that will identify if it is 429. On a previous commit error.error seemed to be giving more details that were in the redux DevTools. 
As for reducing the queries. I think you've got a point about these new endpoints increasing the queries significantly. Perhaps that's why RedditMinimal went through a separate api in Avatar. 

Also, just had a thought. For this error state, I keep having to update it in 4 files if I make a change. Do you think it would be worth setting up an Error component to handle this little bit of jsx?

**Comment by Jbhnd** [comment]
Okay. I'll do a new pull for the error message fix. After doing a bit if searching yesterday, I found an additional query parameter(sr_detail) that we can add to the subreddit posts query, and get the icon_img.

So instead of 'https://www.reddit.com/r/popular.json', the query url would be 'https://www.reddit.com/r/popular.json?sr_detail=1'. It would return the normal response with an additional 'sr_detail' property which has the icon_img and other details. We can use that instead of the subreddit icon query. That would remove the need for all the added queries that run for reddit icons. Let's see if that affects the rate limits.

And yes, I agree that with all those updates in different places, an error component may be better. We should definitely try that option.

**Comment by mattsteen14** [comment]
Thank you so much. I can't tell you how happy I am with this. I work on this yesterday until I have to pick up my son from school & while I'm doing that you're doing this very useful research. I will implement your suggestions & then I think the error component will be next planned PR when these are merged. Otherwise it's going to get messy for me with all these branches.

**Comment by mattsteen14** [comment]
I think most of the work on this is now in pull request #4. At the end of the day, I hope the custom baseQuery is an improvement but it looks like this 429 fetch error will just happen every now & again. We're trying to limit the queries. We will look at an alternative for fetching author icons. I think we just need to decide on the UX for how we explain this to the user. Generally it all needs to be simplified. There does not need FETCH_ERROR etc etc in every section of the app, just in Home then the error states for the other components can be in the console. I think PR#4 is so far ahead that if you approve of that one then I think I'll just merge that, close & delete the branch for this PR, then we can individually look at the error UX & an alternative for the author icons.

**Comment by Jbhnd** [comment]
> Thank you so much. I can't tell you how happy I am with this. I work on this yesterday until I have to pick up my son from school & while I'm doing that you're doing this very useful research. I will implement your suggestions & then I think the error component will be next planned PR when these are merged. Otherwise it's going to get messy for me with all these branches.

You're welcome. I was quite happy to find it too after much searching. Yes, the error component can be postponed for now.

**Comment by Jbhnd** [comment]
> I think most of the work on this is now in pull request #4. At the end of the day, I hope the custom baseQuery is an improvement but it looks like this 429 fetch error will just happen every now & again. We're trying to limit the queries. We will look at an alternative for fetching author icons. I think we just need to decide on the UX for how we explain this to the user. Generally it all needs to be simplified. There does not need FETCH_ERROR etc etc in every section of the app, just in Home then the error states for the other components can be in the console.

Yes. Even after reducing queries, these errors will happen sometimes. We just need the error messages to be descriptive/explanatory, and to display correctly.

> I think PR#4 is so far ahead that if you approve of that one then I think 
I'll just merge that, close & delete the branch for this PR, then we can individually look at the error UX & an alternative for the author icons.

That's a reasonable suggestion. I'll take one last look at PR #4 and comment on there.

**Pull request merged**
