### PR TITLE
redditApiSlice - created hooks to fetch subreddit & author icons / Post.jsx - used those hooks to render subreddit & author icons as other props to render the posts subreddit display name, author display name, post  body & image

### PR DESCRIPTION
**Pull request by mattsteen14**
As the title says in redditApiSlice I created new endpoint queries to fetch icon_img data from the /about.json endpoints for subreddit & author. I then created hooks from these which I imported into Post. I then destructured variables from the hooks to use in the src props of the img tag. 

Screenshot 2024-09-18 at 13 06 45

Also in Post I used JSX expressions within tags to render subreddit name, author name with their icons. Then in the post body I used the selftest property to display the text body of the post. 

Screenshot 2024-09-18 at 13 08 59

I used post.url to render the image posted.

Screenshot 2024-09-18 at 13 09 57

But as you can see, a number of the icons are just not rendering for some reason. We need to keep looking into this.

Screenshot 2024-09-18 at 13 13 19

Also, this is good to show you the general layout that I am after but Post is in desperate need of css.

### CODE REVIEW

**Comment by mattsteen14** [comment]
As the title says in redditApiSlice I created new endpoint queries to fetch icon_img data from the /about.json endpoints for subreddit & author. I then created hooks from these which I imported into Post. I then destructured variables from the hooks to use in the src props of the img tag. 

Screenshot 2024-09-18 at 13 06 45

Also in Post I used JSX expressions within tags to render subreddit name, author name with their icons. Then in the post body I used the selftest property to display the text body of the post. 

Screenshot 2024-09-18 at 13 08 59

I used post.url to render the image posted.

Screenshot 2024-09-18 at 13 09 57

But as you can see, a number of the icons are just not rendering for some reason. We need to keep looking into this.

Screenshot 2024-09-18 at 13 13 19

Also, this is good to show you the general layout that I am after but Post is in desperate need of css.

**Comment by mattsteen14** [comment]
NB - pull request #3 is still in progress which also involves redditApiSlice so I know it's living on the edge but I branched off from the branch to work on top of PR#3s custom base query. Just because I knew that that code would push up the line numbers of this commit. Don't worry. It will work. I just need to make sure I merge pull request #3 first, before I merge this pull request.

**Comment by Jbhnd** [comment]
This all looks good. For the icons/and images that do not load, we should add in fallback images/icons. I can approve after that.

**Comment by mattsteen14** [comment]
> This all looks good. For the icons/and images that do not load, we should add in fallback images/icons. I can approve after that.

Okay. Thanks Joy. I'll have a look at that tomorrow. Do you have any ideas or resources?

**Comment by Jbhnd** [comment]
This link has some icons for reddit https://www.flaticon.com/free-icons/reddit. One of those should be fine as fallback for user icon.

For the subreddit fallback icon, this svg from one of the chats on subreddits should be fine
(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path d="M10 0a10 10 0 1 0 10 10A10.011 10.011 0 0 0 10 0ZM8.016 8.633a1.616 1.616 0 0 0-.2.806V13.5H5.931V6.172h1.8v.9h.039a3.009 3.009 0 0 1 1.018-.732 3.45 3.45 0 0 1 1.449-.284c.246-.003.491.02.732.068.158.024.309.08.444.164l-.759 1.832a2.09 2.09 0 0 0-1.093-.26c-.33-.01-.658.062-.954.208a1.422 1.422 0 0 0-.591.565Zm2.9 6.918H9.355L14.7 2.633c.426.272.828.58 1.2.922l-4.984 11.996Z"></path></svg>)

**Comment by mattsteen14** [comment]
> This link has some icons for reddit https://www.flaticon.com/free-icons/reddit. One of those should be fine as fallback for user icon.
> 
> For the subreddit fallback icon, this svg from one of the chats on subreddits should be fine ()

Ok thanks. Was there meant to be another link there for the subreddit fallback? ^

**Comment by Jbhnd** [comment]
Yes, it's this svg file. Thanks for pointing out that it didn't attach. 
``` <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path d="M10 0a10 10 0 1 0 10 10A10.011 10.011 0 0 0 10 0ZM8.016 8.633a1.616 1.616 0 0 0-.2.806V13.5H5.931V6.172h1.8v.9h.039a3.009 3.009 0 0 1 1.018-.732 3.45 3.45 0 0 1 1.449-.284c.246-.003.491.02.732.068.158.024.309.08.444.164l-.759 1.832a2.09 2.09 0 0 0-1.093-.26c-.33-.01-.658.062-.954.208a1.422 1.422 0 0 0-.591.565Zm2.9 6.918H9.355L14.7 2.633c.426.272.828.58 1.2.922l-4.984 11.996Z"></path></svg> ```

We can add the svg file to the project as an image, then import it into Post component, and set it as fallback in the img element using onError attribute.

``` import subreddit from '../../subreddit.svg'```

then in img element

``` onError={(e) => {e.target.src = subreddit}}```
``` width='50px' height='50px' ```

The inline width and height is temporary, just so the img doesn't take over the whole page. We can remove that when adding css.

**Comment by mattsteen14** [comment]
> Yes, it's this svg file. Thanks for pointing out that it didn't attach. `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path d="M10 0a10 10 0 1 0 10 10A10.011 10.011 0 0 0 10 0ZM8.016 8.633a1.616 1.616 0 0 0-.2.806V13.5H5.931V6.172h1.8v.9h.039a3.009 3.009 0 0 1 1.018-.732 3.45 3.45 0 0 1 1.449-.284c.246-.003.491.02.732.068.158.024.309.08.444.164l-.759 1.832a2.09 2.09 0 0 0-1.093-.26c-.33-.01-.658.062-.954.208a1.422 1.422 0 0 0-.591.565Zm2.9 6.918H9.355L14.7 2.633c.426.272.828.58 1.2.922l-4.984 11.996Z"></path></svg>`
> 
> We can add the svg file to the project as an image, then import it into Post component, and set it as fallback in the img element using onError attribute.
> 
> ` import subreddit from '../../subreddit.svg'`
> 
> then in img element
> 
> ` onError={(e) => {e.target.src = subreddit}}` `width='50px' height='50px'`
> 
> The inline width and height is temporary, just so the img doesn't take over the whole page. We can remove that when adding css.

Was the svg from what wilaxx posted before? I used chatGPT to make something. It's a placeholder for now as it's not the same as the r/ but it would be great if we could match the style. Do you know anything about making svgs?

**Comment by mattsteen14** [comment]
I've added fallback images & used json?sr_detail=1 to reduce the queries for fetching subreddit data. The author icon is still being fetched from /about.json so we may need to look for an alternative there circling back to Avatar.jsx. But let me know what you think, if this achieves what I set out for Post.jsx for now.

**Comment by Jbhnd** [comment]
> Was the svg from what wilaxx posted before? I used chatGPT to make something. It's a placeholder for now as it's not the same as the r/ but it would be great if we could match the style. Do you know anything about making svgs?

Yes, it was. I remembered it was suggested for the subreddit avatar. So until we get something better, I felt it was okay. About the fallback author img matching that style, I actually prefer it to be much different. I was thinking something closer to icons like below from reddit. Some sites(one example- https://icons8.com/icons/set/reddit) already have svgs of those type of icons. So I only use them, haven't had to make any myself. It's nice that you made this one easily with chatGTP.

image

**Comment by mattsteen14** [comment]
Ok that's cool. I like my userLogo. I was able to make it better than what chatGPT initially suggested. I'd want both to be aligned. That's why I like what I've set atm. Unless you can find something similar ish for subreddits.

**Review by Jbhnd — APPROVED** [review]
Approving this pull request. You've made updates from my feedback to use 'sr-detail' in the posts query in order to reduce the number of api requests. Also, you've implemented the fallback image mentioned, and even created an additional svg fallback image. In PR #3 we've discussed other things to work on, including looking to further reduce the number of api requests, creating an Error component, and/or improving on the error messages displayed when rate limits are reached. Nice work overall.

**Pull request closed without merging**
